### PR TITLE
gcc-8.0 fixes, minor cleanups

### PR DESCRIPTION
**Pull request by whoozle**

### CODE REVIEW

**Comment by guillaumechereau** [comment]
Thanks! I am a bit busy these days, I'll check that this week end probably, after I finish merging the new marching cube algo!

**Comment by NotAFile** [comment]
Seems to work great. Current master does not compile for me, but this compiles and works fine.

**Comment by mdtrooper** [comment]
```
$ git branch
  master
* pr/116
md@speccy-laptop:/tmp/goxel$ make release
scons debug=0
scons: Reading SConscript files ...
Checking whether __GLIBC__ is declared... (cached) yes
Checking for C library libpng... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
gcc -o ext_src/inih/ini.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -DINI_HANDLER_LINENO=1 -Werror -O3 -DNDEBUG -Ofast -pthread -DHAVE_LIBPNG=1 -DCYCLES_STD_UNORDERED_MAP "-DCCL_NAMESPACE_BEGIN=namespace ccl {" -DCCL_NAMESPACE_END=} -DWITH_CUDA_DYNLOAD -DWITHOUT_OPENIMAGEIO -DWITH_GLEW_MX -DWITH_CYCLES -fno-var-tracking-assignments -Wno-sign-compare -Wno-strict-aliasing -Wno-uninitialized -Isrc -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/inih -Iext_src/cycles/src -Iext_src/cycles/third_party/atomic ext_src/inih/ini.c
In function ‘strncpy0’,
    inlined from ‘ini_parse_stream’ at ext_src/inih/ini.c:166:17:
ext_src/inih/ini.c:73:5: error: ‘strncpy’ specified bound 50 equals destination size [-Werror=stringop-truncation]
     strncpy(dest, src, size);
     ^~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy0’,
    inlined from ‘ini_parse_stream’ at ext_src/inih/ini.c:142:17:
ext_src/inih/ini.c:73:5: error: ‘strncpy’ specified bound 50 equals destination size [-Werror=stringop-truncation]
     strncpy(dest, src, size);
     ^~~~~~~~~~~~~~~~~~~~~~~~
ext_src/inih/ini.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-unknown-warning-option’ [-Werror]
cc1: error: unrecognized command line option ‘-Wno-unknow-pragma’ [-Werror]
cc1: all warnings being treated as errors
scons: *** [ext_src/inih/ini.o] Error 1
scons: building terminated because of errors.
make: *** [Makefile:8: release] Error 2
md@speccy-laptop:/tmp/goxel$ 
```

**Comment by guillaumechereau** [comment]
Thanks,  I still think a proper solution would be to get ride of cycles totally.  I am a bit thinking of implementing my own simple ray tracer for goxel.  I guess as soon as I get a week free of other work I'll try to test the idea.

**Comment by guillaumechereau** [comment]
OK I totally removed cycles, since the code is too hard to maintain.  Should solve the problem ;)
Thanks for you time!

**Pull request closed without merging**
