### PR TITLE
Fix image plane to mesh conversion

### PR DESCRIPTION
**Pull request by ravencgg**
Fixes a crash in the memcpy on non-square images.
Fixes the orientation and placement of the mesh.

### CODE REVIEW

**Comment by guillaumechereau** [comment]
Hello, what bug is this fixing exactly?  I tried the patch and turning an image layer into a mesh now seems to revert the image.

**Comment by guillaumechereau** [comment]
Oh I see, there is indeed a memory bug.  Your patch fixes it, but now the mesh is flipped somehow.

**Comment by ravencgg** [comment]
You're right, my test image was symmetrical on the x axis so I missed it. Fixed in latest commit.

**Comment by guillaumechereau** [comment]
Thanks!

**Pull request merged**
