### PR TITLE
Model 3D export

### PR DESCRIPTION
**Pull request by bztsrc**
More and more people are asking for this. So much that I really need this. This just a single file without any dependencies, it won't bother you, but it would make users happy.

Let's make a deal. If you accept this PR then in return I'll fix some of the file import/export issues. For example, adding material support to obj files or handling vox layers.

Deal?

Cheers,
bzt

### CODE REVIEW

**Comment by bztsrc** [comment]
Just some issues I could help with in exchange:
issue #224
issue #208
issue #203
issue #159
issue #135

Cheers,
bzt

**Comment by bztsrc** [comment]
Please?

**Comment by hellocatfood** [comment]
It's not an ideal solution but until this PR is merged you could export as .vox and then use a .vox blender importer (e.g. https://github.com/technistguru/MagicaVoxel_Importer or https://github.com/RichysHub/MagicaVoxel-VOX-importer ) to import into blender and then export as .obj or other file format.

Until then I guess the other issues can still be worked on?

**Comment by bztsrc** [comment]
> It's not an ideal solution but until this PR is merged you could export as .vox and then use a .vox blender importer

Thanks, I already have a better solution, [m3dconv](https://gitlab.com/bztsrc/model3d/tree/master/m3dconv) can directly convert .vox (and many other formats) into .m3d, and I also have [mtsedit](https://gitlab.com/bztsrc/mtsedit/blob/master/docs/import.md) which can import .gox (Goxel native) or .vox (although that code is limited to 256x256x256 volume). The issue is, all of these require an additional step, and that's what my users are complaining about.

It is possible to create voxel models in Blender and then export with the [Blender .m3d exporter](https://gitlab.com/bztsrc/model3d/-/tree/master/blender) too, but using Blender for that is cumbersome, my users would like to use Goxel because it is a lot more simpler and user friendlier.

But thanks for the suggestion, anyway.

> Until then I guess the other issues can still be worked on?

I am. But I don't want to share anything because I haven't heard from guillaumechereau as of yet.

Cheers,
bzt

**Comment by hellocatfood** [comment]
Was this closed because it was fixed/merged?

**Comment by bztsrc** [comment]
> Was this closed because it was fixed/merged?

Sadly no. @guillaumechereau closes my issues without any comments for some reason. I don't know what's his issue with this patch, but I really would like to know. It is a separate file, would merge without conflicts.

Cheers,
bzt

**Comment by guillaumechereau** [comment]
I closed because I don't want to add support for non well known formats, adding complexity to the software.  For this kind of things the best is I think to use an intermediary format as suggested.  If goxel had support for plugins that would also be a good fit.

**Comment by pegvin** [comment]
You should've just looked into model3d format not saying to merge it, it's really just 1 c file and it's highly efficient and that's why i chose it over the default gox format.

**Pull request closed without merging**
