### PR TITLE
Added a first version of export to a file from the command line

### PR DESCRIPTION
**Pull request by mdtrooper**
Hi again.

I need for to make more easy the task to create sprites a some arguments in the command line, as this --export=FILE.

The only thing that is not made, it is the export to vox format, sorry I have been trying to make but I could not.

Regards.

### CODE REVIEW

**Comment by guillaumechereau** [comment]
Hi Miguel.  Thanks for the work, alas I don't think this is the proper way to handle export.  This part of the code is not very clean yet, but the right way would be to use the internal registered actions so that we can automatically save to any registered format.  I think I rather clean up the export code before adding the command line option.  I'll try to do that soon.

**Comment by mdtrooper** [comment]
Yes, it sounds good. I will try to get some spare time for to change the code as you said.

**Comment by guillaumechereau** [comment]
But actually, this feature by itself is not very useful unless we can save the rendering settings in the goxel native file format.  Otherwise how do you set the camera position when using --export?

**Comment by mdtrooper** [comment]
You think in this case as me, because I have been working in a third branch as you can see.

This third branch will have two buttons (load and save) for to save the actual render options as file in ini format. And there is another code for to set a new command line arg for to set a render options.

Thanks and regards.

**Comment by mdtrooper** [comment]
Could you close this pull request? Because you have been working in the project and the code is more advance than my old code.

I want to made this feature but with better code. Maybe I will try in the next weeks.

Thanks.

**Comment by guillaumechereau** [comment]
OK, thanks for the pull request anyway.  I think even when things don't get merged, it is always good because it helps to think about the future features.  I have indeed changed the action code quite a bit, the code is now slightly better than before, but still messy.  I wouldn't be surprised if it goes through an other re-factorization at some point.

**Pull request closed without merging**
