### PR TITLE
Pico 8 palette

### PR DESCRIPTION
**Pull request by LatorreDev**
I added the famous pico 8 palette from the fantasy console [pico8palette](https://pico-8.fandom.com/wiki/Palette#:~:text=Every%20pixel%20on%20PICO%2D8,has%20three%20layers%20of%20palettes.)

I compiled again goxel and the new palette is working 
Image working [here](https://ibb.co/3WWH4BW)

Also correct missing parethesis on python file and added the full command to install dependencies under Debian and based distros

### CODE REVIEW

**Comment by guillaumechereau** [comment]
Hi.  Thanks for the PR.  Can you make a separate PR request to add yourself in the CLA before I have a look?

**Comment by guillaumechereau** [comment]
Hello LatorreDev,

Before I check the PR, can you make a new PR that adds yourself to the list individual CLA, as explained here:
https://github.com/guillaumechereau/goxel/blob/master/CONTRIBUTING.md

I need that to keep the right to license goxel on iOS.

**Comment by LatorreDev** [comment]
Done!

**Comment by guillaumechereau** [comment]
OK thanks, I merged into master!

**Pull request closed without merging**
