### PR TITLE
Add hardening flags

### PR DESCRIPTION
**Pull request by FedericoCeratto**
Enabled by default.

### CODE REVIEW

**Comment by guillaumechereau** [comment]
Travis complains about this one:
gcc: error: unrecognized command line option ‘-fstack-protector-strong’

**Comment by guillaumechereau** [comment]
Sorry coming back to this project after a long period of inactivity.   I feel like some of those hardening flags should just be the default instead of using a special 'security' argument for it.  What is the advantage of using -fPIE ?

**Comment by hendursaga** [comment]
> What is the advantage of using -fPIE ?

Not just security benefits, but have a look at https://en.wikipedia.org/wiki/Position-independent_code#Position-independent_executables

**Comment by guillaumechereau** [comment]
I close this PR for the moment since I don't think it is worth having a 'security' build variant.  I still think the build flags could be improved for static analysis if possible.

**Pull request closed without merging**
