### PR TITLE
Set camera with numeric values

### PR DESCRIPTION
**Pull request by mdtrooper**
I was working in the added some widgets to set the camera "fine tune".

Because I want to use the goxel to create some sprites for a videogame and need that the camera is ever in the same position.

Do you think that is correct?

screenshot at 2016-08-09 00 03 31

### CODE REVIEW

**Comment by guillaumechereau** [comment]
Seems good.  I will check it in detail later tonight.

**Comment by guillaumechereau** [comment]
I had a look at the code.  A few comments:
- The inputs for angles should show values in degrees, not radiant.
- I don't really like to have all the labels on a different column. It should look more like::

        = Offset =
        [1  - +] x
        [2  - +] y
        [0  - +] z
        = Rotation =
        [1° - +] x
        [2° - +] y
        [0° - +] z

**Comment by mdtrooper** [comment]
Sorry, I wrote the message in another pull request. 
I write again:

""""
Yes, it sounds good. I will try to get some spare time for to change the code as you said.
""""

**Comment by mdtrooper** [comment]
Well, I followed your advise, the task to show as euler angles (in degrees and each axis) was very dificult for me, but I think it is done. The only task is missing is show as [1° - +] x, but give me some days to make it.

**Comment by guillaumechereau** [comment]
Ah yes it's nice to have a quat_to_euler function in vec.h.  This will probably come in handy in other places too.  Thanks.

**Comment by mdtrooper** [comment]
[Copy&Paste from other pullrequest]

Could you close this pull request? Because you have been working in the project and the code is more advance than my old code.

I want to made this feature but with better code. Maybe I will try in the next weeks.

Thanks.

**Comment by guillaumechereau** [comment]
Hi, OK will close it, sorry I lost track of this patch.  I am going to make a new release soon, after that I think I will start to check how to have a setting file to set the camera position.

**Pull request closed without merging**
